In [4]:
# pip install --upgrade pyarrow shapely geopandas



### **5. Integración con Mapbox.ipynb**
  - **5.1. Preparativos para Mapbox:** Configuraciones iniciales y conexiones.
  - **5.2. Carga de Tilesets a Mapbox:** 
    - **5.2.1.** Eliminación de tilesets existentes.
    - **5.2.2.** Carga de nuevos tilesets.
  - **5.3. Actualización y personalización de estilos:** 
    - **5.3.1.** Recuperación y edición del JSON de estilo existente.
    - **5.3.2.** Aplicación de cambios de formato y estilo en el mapa.

In [5]:
# -------------------
# Parameters and Configuration
# -------------------

# FRAC = 0.01
# START_YEAR = 2023
# END_YEAR = 2026

In [6]:
import time
import pandas as pd
import os

## Tilesets Upload

In [7]:

import os

# Verifica si el archivo existe
def check_file_exists(file_path):
    if not os.path.exists(file_path):
        print(f"Error: El archivo {file_path} no existe.")
        return False
    return True

In [8]:
import json

# Verifica si el archivo JSON es válido y no está vacío
def check_valid_json(file_path):
    try:
        with open(file_path, 'r') as file:
            data = json.load(file)
            if not data:
                print(f"Error: El archivo {file_path} está vacío.")
                return False
    except json.JSONDecodeError:
        print(f"Error: El archivo {file_path} no contiene un JSON válido.")
        return False
    return True

In [9]:
# source
# Tileset "matuteiglesias2.income_P202408" does not exist

In [10]:

groups = ["H", "P", "M24", "M6", "M14"]

PATH_POBREZA = './../data'

# Setting the environment variable
os.environ["MAPBOX_ACCESS_TOKEN"] = "sk.eyJ1IjoibWF0dXRlaWdsZXNpYXMyIiwiYSI6ImNrb3lvMWZyajAxZncycG8ycnJkaTI1ZjYifQ.LXJGImmBgQtWWrNOC1wTcA"

year_month = str(pd.Timestamp.now().year) + str(pd.Timestamp.now().month).zfill(2)
# year_month = '202309c'

# Function to determine the next available version
def get_next_version(tileset_name_base, username):
    version = 0
    while True:
        tileset_name = f"{tileset_name_base}_v{version}"
        result = os.system(f"tilesets list {username} | grep {tileset_name}")
        if result != 0:  # If tileset name does not exist
            return tileset_name, version
        version += 1


def get_current_version(tileset_name_base, username):
    version = 0
    latest_version = None
    while True:
        tileset_name = f"{tileset_name_base}_v{version}"
        result = os.system(f"tilesets list {username} | grep {tileset_name}")
        if result != 0:  # If tileset name does not exist, the loop should stop
            break
        latest_version = version
        version += 1
    
    if latest_version is not None:
        return f"{tileset_name_base}_v{latest_version}", latest_version
    else:
        return None, None  # No versions found

# Example usage
username = "matuteiglesias2"
# tileset_name_base = f"matuteiglesias2.income_H202408"
# tileset_name, version = get_next_version(tileset_name_base, username)
# print(f"Next available tileset: {tileset_name} (version: {version})")



for group in groups:
    print(f"Processing group: {group}")
    
    # Determine the base name and next available version for the tileset
    tileset_name_base = f"matuteiglesias2.income_{group}{year_month}"
    tileset_name, version = get_next_version(tileset_name_base, username)
    
    print(f"Using tileset name: {tileset_name} (version: {version})")
    
    # Delete sources and tileset
    os.system(f"tilesets delete-source -f matuteiglesias2 income_provs_{group}")
    os.system(f"tilesets delete-source -f matuteiglesias2 income_dptos_{group}")
    os.system(f"tilesets delete-source -f matuteiglesias2 income_fracs_{group}")
    time.sleep(3)
    
    # Upload sources
            # if not ow and os.path.exists(f'poverty_{filename_prefix}_{geo_level}_sample{FRAC}.geojson'): continue

    os.system(f"tilesets upload-source matuteiglesias2 income_provs_{group} {PATH_POBREZA}/geojson/poverty_{group}_PROV.geojson")
    os.system(f"tilesets upload-source matuteiglesias2 income_dptos_{group} {PATH_POBREZA}/geojson/poverty_{group}_DPTO.geojson")
    os.system(f"tilesets upload-source matuteiglesias2 income_fracs_{group} {PATH_POBREZA}/geojson/poverty_{group}_IDFRAC.geojson")
    time.sleep(3)
    
    # Create tilesets
    os.system(f"tilesets create {tileset_name} --recipe {PATH_POBREZA}/recipes/pobreza_{group}-recipe.json --name 'Ingresos y Pobreza - {group} {year_month} v{version}'")
    time.sleep(3)
    os.system(f"tilesets publish {tileset_name}")
    
print("Processing completed.")

Processing group: H

matuteiglesias2.income_H202408_v0
matuteiglesias2.income_H202408_v1
matuteiglesias2.income_H202408_v2
matuteiglesias2.income_H202408_v3
matuteiglesias2.income_H202408_v4
Using tileset name: matuteiglesias2.income_H202408_v5 (version: 5)
Source deleted.
Source deleted.
Source deleted.
upload progress
{"id": "mapbox://tileset-source/matuteiglesias2/income_provs_H", "files": 1, "source_size": 45412249, "file_size": 45412249}
upload progress
{"id": "mapbox://tileset-source/matuteiglesias2/income_dptos_H", "files": 1, "source_size": 63601934, "file_size": 63601934}
upload progress
{"id": "mapbox://tileset-source/matuteiglesias2/income_fracs_H", "files": 1, "source_size": 164277339, "file_size": 164277339}
{"message": "Successfully created empty tileset matuteiglesias2.income_H202408_v5. Publish your tileset to begin processing your data into tiles."}
{"message": "Processing matuteiglesias2.income_H202408_v5", "jobId": "cm0cmwm9b001a08mc121tagv0"}
Processing group: P

✔ Tileset job received. Visit https://studio.mapbox.com/tilesets/matuteiglesias2.income_H202408_v5 or run tilesets job matuteiglesias2.income_H202408_v5 cm0cmwm9b001a08mc121tagv0 to view the status of your tileset.

matuteiglesias2.income_P202408_v0
matuteiglesias2.income_P202408_v1
matuteiglesias2.income_P202408_v2
matuteiglesias2.income_P202408_v3
Using tileset name: matuteiglesias2.income_P202408_v4 (version: 4)
Source deleted.
Source deleted.
Source deleted.
upload progress
{"id": "mapbox://tileset-source/matuteiglesias2/income_provs_P", "files": 1, "source_size": 45416254, "file_size": 45416254}
upload progress
{"id": "mapbox://tileset-source/matuteiglesias2/income_dptos_P", "files": 1, "source_size": 63689334, "file_size": 63689334}
upload progress
{"id": "mapbox://tileset-source/matuteiglesias2/income_fracs_P", "files": 1, "source_size": 165117072, "file_size": 165117072}
{"message": "Successfully created empty tileset matuteiglesias2.income_P202408_v4. Publish your tileset to begin processing your data into tiles."}
{"message": "Processing matuteiglesias2.income_P202408_v4", "jobId": "cm0cmz5ne001g08mc91x9ezo4"}
Processing group: M24

✔ Tileset job received. Visit https://studio.mapbox.com/tilesets/matuteiglesias2.income_P202408_v4 or run tilesets job matuteiglesias2.income_P202408_v4 cm0cmz5ne001g08mc91x9ezo4 to view the status of your tileset.

matuteiglesias2.income_M24202408_v0
matuteiglesias2.income_M24202408_v1
matuteiglesias2.income_M24202408_v2
Using tileset name: matuteiglesias2.income_M24202408_v3 (version: 3)
Source deleted.
Source deleted.
Source deleted.
upload progress
{"id": "mapbox://tileset-source/matuteiglesias2/income_provs_M24", "files": 1, "source_size": 45416461, "file_size": 45416461}
upload progress
{"id": "mapbox://tileset-source/matuteiglesias2/income_dptos_M24", "files": 1, "source_size": 63693802, "file_size": 63693802}
upload progress
{"id": "mapbox://tileset-source/matuteiglesias2/income_fracs_M24", "files": 1, "source_size": 164808565, "file_size": 164808565}
{"message": "Successfully created empty tileset matuteiglesias2.income_M24202408_v3. Publish your tileset to begin processing your data into tiles."}
{"message": "Processing matuteiglesias2.income_M24202408_v3", "jobId": "cm0cn24x2000008l76t4u72yv"}
Processing group: M6

✔ Tileset job received. Visit https://studio.mapbox.com/tilesets/matuteiglesias2.income_M24202408_v3 or run tilesets job matuteiglesias2.income_M24202408_v3 cm0cn24x2000008l76t4u72yv to view the status of your tileset.

matuteiglesias2.income_M6202408_v0
matuteiglesias2.income_M6202408_v1
matuteiglesias2.income_M6202408_v2
Using tileset name: matuteiglesias2.income_M6202408_v3 (version: 3)
Source deleted.
Source deleted.
Source deleted.
upload progress
{"id": "mapbox://tileset-source/matuteiglesias2/income_provs_M6", "files": 1, "source_size": 45415747, "file_size": 45415747}
upload progress
{"id": "mapbox://tileset-source/matuteiglesias2/income_dptos_M6", "files": 1, "source_size": 62971195, "file_size": 62971195}
upload progress
{"id": "mapbox://tileset-source/matuteiglesias2/income_fracs_M6", "files": 1, "source_size": 144624750, "file_size": 144624750}
{"message": "Successfully created empty tileset matuteiglesias2.income_M6202408_v3. Publish your tileset to begin processing your data into tiles."}
{"message": "Processing matuteiglesias2.income_M6202408_v3", "jobId": "cm0cn4q7v004x08l73pbl1rpi"}
Processing group: M14

✔ Tileset job received. Visit https://studio.mapbox.com/tilesets/matuteiglesias2.income_M6202408_v3 or run tilesets job matuteiglesias2.income_M6202408_v3 cm0cn4q7v004x08l73pbl1rpi to view the status of your tileset.

matuteiglesias2.income_M14202408_v0
matuteiglesias2.income_M14202408_v1
matuteiglesias2.income_M14202408_v2
Using tileset name: matuteiglesias2.income_M14202408_v3 (version: 3)
Source deleted.
Source deleted.
Source deleted.
upload progress
{"id": "mapbox://tileset-source/matuteiglesias2/income_provs_M14", "files": 1, "source_size": 45415878, "file_size": 45415878}
upload progress
{"id": "mapbox://tileset-source/matuteiglesias2/income_dptos_M14", "files": 1, "source_size": 63680637, "file_size": 63680637}
upload progress
{"id": "mapbox://tileset-source/matuteiglesias2/income_fracs_M14", "files": 1, "source_size": 152367424, "file_size": 152367424}
{"message": "Successfully created empty tileset matuteiglesias2.income_M14202408_v3. Publish your tileset to begin processing your data into tiles."}
{"message": "Processing matuteiglesias2.income_M14202408_v3", "jobId": "cm0cn7bkq001v08mccz5e0ywo"}
Processing completed.

✔ Tileset job received. Visit https://studio.mapbox.com/tilesets/matuteiglesias2.income_M14202408_v3 or run tilesets job matuteiglesias2.income_M14202408_v3 cm0cn7bkq001v08mccz5e0ywo to view the status of your tileset.

In [11]:

    # os.system(f"tilesets upload-source matuteiglesias2 income_provs_{group} {PATH_POBREZA}/geojson/poverty_{group}_PROV.geojson")
    # os.system(f"tilesets upload-source matuteiglesias2 income_dptos_{group} {PATH_POBREZA}/geojson/poverty_{group}_DPTO.geojson")
    # os.system(f"tilesets upload-source matuteiglesias2 income_fracs_{group} {PATH_POBREZA}/geojson/poverty_{group}_IDFRAC.geojson")

In [12]:
# !tilesets publish matuteiglesias2.income_H202408_v1

In [13]:
# !tilesets job matuteiglesias2.income_H202408_v1 cm0bgo961002x08l5a8ff024l

# {"id": "cm0bgo961002x08l5a8ff024l", "stage": "success", "tilesetId": "matuteiglesias2.income_H202408_v1", "errors": [], "completed": 1724704772950, "created": 1724704743529, "created_nice": "Mon Aug 26 2024 20:39:03 GMT+0000 (Coordinated Universal Time)", "published": 1724704743529, "warnings": [], "layer_stats": {"income-dptos": {"total_tiles": 4273, "minzoom": 0, "maxzoom": 10, "capped": 0, "checksum": 541833105, "polygon_count": 14872, "linestring_count": 0, "point_count": 0, "zooms": {"0": {"xmin": 0, "xmax": 0, "ymin": 0, "ymax": 0, "sum_size": 110790, "max_size": 110790, "avg_size": 110790, "sum_area": 508164394.246, "capped": 0, "tiles": 1, "size_histogram": [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], "capped_list": []}, "1": {"xmin": 0, "xmax": 0, "ymin": 1, "ymax": 1, "sum_size": 141299, "max_size": 141299, "avg_size": 141299, "sum_area": 127041098.562, "capped": 0, "tiles": 1, "size_histogram": [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], "capped_list": []}, "2": {"xmin": 1, "xmax": 1, "ymin": 2, "ymax": 2, "sum_size": 153497, "max_size": 153497, "avg_size": 153497, "sum_area": 58476014.26, "capped": 0, "tiles": 1, "size_histogram": [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], "capped_list": []}, "3": {"xmin": 2, "xmax": 2, "ymin": 4, "ymax": 5, "sum_size": 169652, "max_size": 156804, "avg_size": 84826, "sum_area": 29238007.13, "capped": 0, "tiles": 2, "size_histogram": [1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], "capped_list": []}, "4": {"xmin": 4, "xmax": 5, "ymin": 8, "ymax": 10, "sum_size": 198118, "max_size": 152583, "avg_size": 39623.6, "sum_area": 20402900.081, "capped": 0, "tiles": 5, "size_histogram": [3, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], "capped_list": []}, "5": {"xmin": 9, "xmax": 11, "ymin": 17, "ymax": 21, "sum_size": 234288, "max_size": 88077, "avg_size": 23428.8, "sum_area": 9895902.373, "capped": 0, "tiles": 10, "size_histogram": [8, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], "capped_list": []}, "6": {"xmin": 18, "xmax": 22, "ymin": 35, "ymax": 43, "sum_size": 307604, "max_size": 52893, "avg_size": 12816.833, "sum_area": 5860607.409, "capped": 0, "tiles": 24, "size_histogram": [20, 3, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], "capped_list": []}, "7": {"xmin": 37, "xmax": 44, "ymin": 71, "ymax": 87, "sum_size": 453695, "max_size": 29348, "avg_size": 6301.319, "sum_area": 4368183.004, "capped": 0, "tiles": 72, "size_histogram": [71, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], "capped_list": []}, "8": {"xmin": 75, "xmax": 89, "ymin": 143, "ymax": 175, "sum_size": 755570, "max_size": 24708, "avg_size": 3201.568, "sum_area": 3640328.967, "capped": 0, "tiles": 236, "size_histogram": [236, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], "capped_list": []}, "9": {"xmin": 151, "xmax": 179, "ymin": 287, "ymax": 350, "sum_size": 1536427, "max_size": 19392, "avg_size": 1848.889, "sum_area": 3238813.406, "capped": 0, "tiles": 831, "size_histogram": [831, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], "capped_list": []}, "10": {"xmin": 302, "xmax": 359, "ymin": 575, "ymax": 700, "sum_size": 3848050, "max_size": 11919, "avg_size": 1245.324, "sum_area": 3025639.979, "capped": 0, "tiles": 3090, "size_histogram": [3090, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], "capped_list": []}}}, "income-fracs": {"total_tiles": 4100, "minzoom": 5, "maxzoom": 10, "capped": 0, "checksum": 152765048, "polygon_count": 44468, "linestring_count": 0, "point_count": 0, "zooms": {"5": {"xmin": 9, "xmax": 11, "ymin": 17, "ymax": 21, "sum_size": 1331108, "max_size": 616791, "avg_size": 133110.8, "sum_area": 9895902.373, "capped": 0, "tiles": 10, "size_histogram": [4, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1], "capped_list": []}, "6": {"xmin": 18, "xmax": 22, "ymin": 35, "ymax": 43, "sum_size": 1702981, "max_size": 544959, "avg_size": 70957.542, "sum_area": 5860607.409, "capped": 0, "tiles": 24, "size_histogram": [12, 3, 3, 0, 3, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], "capped_list": []}, "7": {"xmin": 37, "xmax": 44, "ymin": 71, "ymax": 87, "sum_size": 2068574, "max_size": 398937, "avg_size": 30420.206, "sum_area": 4144693.365, "capped": 0, "tiles": 68, "size_histogram": [42, 15, 7, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0], "capped_list": []}, "8": {"xmin": 75, "xmax": 89, "ymin": 143, "ymax": 174, "sum_size": 2598476, "max_size": 386386, "avg_size": 11347.057, "sum_area": 3560073.544, "capped": 0, "tiles": 229, "size_histogram": [206, 21, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0], "capped_list": []}, "9": {"xmin": 151, "xmax": 179, "ymin": 287, "ymax": 349, "sum_size": 3743476, "max_size": 313751, "avg_size": 4627.288, "sum_area": 3174774.578, "capped": 0, "tiles": 809, "size_histogram": [798, 9, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0], "capped_list": []}, "10": {"xmin": 302, "xmax": 359, "ymin": 575, "ymax": 699, "sum_size": 6604198, "max_size": 191715, "avg_size": 2231.148, "sum_area": 2928394.851, "capped": 0, "tiles": 2960, "size_histogram": [2950, 7, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], "capped_list": []}}}, "income-provs": {"total_tiles": 29233, "minzoom": 0, "maxzoom": 10, "capped": 0, "checksum": 1212639217, "polygon_count": 30439, "linestring_count": 0, "point_count": 0, "zooms": {"0": {"xmin": 0, "xmax": 0, "ymin": 0, "ymax": 0, "sum_size": 9508, "max_size": 9508, "avg_size": 9508, "sum_area": 508164394.246, "capped": 0, "tiles": 1, "size_histogram": [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], "capped_list": []}, "1": {"xmin": 0, "xmax": 0, "ymin": 1, "ymax": 1, "sum_size": 10838, "max_size": 10838, "avg_size": 10838, "sum_area": 127041098.562, "capped": 0, "tiles": 1, "size_histogram": [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], "capped_list": []}, "2": {"xmin": 1, "xmax": 1, "ymin": 2, "ymax": 3, "sum_size": 14804, "max_size": 11648, "avg_size": 7402, "sum_area": 63520549.281, "capped": 0, "tiles": 2, "size_histogram": [2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], "capped_list": []}, "3": {"xmin": 2, "xmax": 3, "ymin": 4, "ymax": 7, "sum_size": 24284, "max_size": 9888, "avg_size": 3469.143, "sum_area": 42614408.799, "capped": 0, "tiles": 7, "size_histogram": [7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], "capped_list": []}, "4": {"xmin": 4, "xmax": 6, "ymin": 8, "ymax": 15, "sum_size": 46355, "max_size": 10637, "avg_size": 2439.737, "sum_area": 29087021.729, "capped": 0, "tiles": 19, "size_histogram": [19, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], "capped_list": []}, "5": {"xmin": 9, "xmax": 13, "ymin": 17, "ymax": 31, "sum_size": 88300, "max_size": 9185, "avg_size": 1839.583, "sum_area": 14237048.305, "capped": 0, "tiles": 48, "size_histogram": [48, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], "capped_list": []}, "6": {"xmin": 18, "xmax": 27, "ymin": 35, "ymax": 63, "sum_size": 202145, "max_size": 9697, "avg_size": 1312.63, "sum_area": 9051250.15, "capped": 0, "tiles": 154, "size_histogram": [154, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], "capped_list": []}, "7": {"xmin": 37, "xmax": 55, "ymin": 71, "ymax": 127, "sum_size": 491562, "max_size": 11750, "avg_size": 1045.877, "sum_area": 6242519.809, "capped": 0, "tiles": 470, "size_histogram": [470, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], "capped_list": []}, "8": {"xmin": 75, "xmax": 110, "ymin": 143, "ymax": 255, "sum_size": 1387013, "max_size": 8542, "avg_size": 881.203, "sum_area": 5019579.754, "capped": 0, "tiles": 1574, "size_histogram": [1574, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], "capped_list": []}, "9": {"xmin": 150, "xmax": 220, "ymin": 287, "ymax": 511, "sum_size": 4538693, "max_size": 6944, "avg_size": 797.802, "sum_area": 4348682.555, "capped": 0, "tiles": 5689, "size_histogram": [5689, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], "capped_list": []}, "10": {"xmin": 301, "xmax": 440, "ymin": 575, "ymax": 1023, "sum_size": 16109376, "max_size": 4745, "avg_size": 757.447, "sum_area": 3976659.036, "capped": 0, "tiles": 21268, "size_histogram": [21268, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], "capped_list": []}}}}, "tileset_precisions": {"10m": 20772464.968000002}, "cu": 0.78, "filesize": 273291522, "recipe": {"version": 1, "layers": {"income-provs": {"source": "mapbox://tileset-source/matuteiglesias2/income_provs_H", "minzoom": 0, "maxzoom": 10}, "income-dptos": {"source": "mapbox://tileset-source/matuteiglesias2/income_dptos_H", "minzoom": 0, "maxzoom": 10}, "income-fracs": {"source": "mapbox://tileset-source/matuteiglesias2/income_fracs_H", "minzoom": 5, "maxzoom": 10}}}}

In [14]:
# Tileset "matuteiglesias2.income_H202408_v1" does not exist

## Mapbox Styles Update

- Fetch the existing style JSON file.
- Update the sources element in the style JSON.
- Upload the updated style JSON back to Mapbox.

### Plantilla base para Mapas de Pobreza

In [15]:
import json
import requests

# Step 1: Fetch the existing style JSON file
# Use the "Retrieve a style" endpoint to get the current style JSON 
# Replace {username} and {style_id} with your Mapbox account and style ID
username = 'matuteiglesias2'
style_id = 'clmtqn2h705bg01p7424h77y3'

access_token = 'sk.eyJ1IjoibWF0dXRlaWdsZXNpYXMyIiwiYSI6ImNrb3lvMWZyajAxZncycG8ycnJkaTI1ZjYifQ.LXJGImmBgQtWWrNOC1wTcA'
url = f"https://api.mapbox.com/styles/v1/{username}/{style_id}?access_token={access_token}"
response = requests.get(url)
template_json = response.json()
STYLE_TEMPLATE = './template01.json'
with open(STYLE_TEMPLATE, 'w') as f:
    json.dump(template_json, f)

In [16]:
template = json.load(open(STYLE_TEMPLATE))

In [17]:
template_json['sources']['composite']['url']

'mapbox://mapbox.mapbox-streets-v8,mapbox.mapbox-terrain-v2,matuteiglesias2.income_M14202309,matuteiglesias2.ejido'

### Wrappers para editar Plantilla

In [18]:
def set_name(style_json, new_name):
    modified_json = style_json.copy()
    modified_json['name'] = new_name
    return modified_json

def set_center_and_zoom(style_json, center, zoom):
    modified_json = style_json.copy()
    modified_json['center'] = center
    modified_json['zoom'] = zoom
    return modified_json

def update_source_url(style_json, new_part):
    modified_json = style_json.copy()
    url = modified_json['sources']['composite']['url']
    
    # Split the URL on commas
    parts = url.split(',')
    
    # Iterate over each part and look for the part that starts with "matuteiglesias2." and contains "income"
    for i, part in enumerate(parts):
        if part.startswith("matuteiglesias2.") and "income" in part:
            parts[i] = new_part
    
    # Reconstruct the URL
    modified_json['sources']['composite']['url'] = ','.join(parts)
    print(modified_json['sources']['composite']['url'])
    return modified_json

## VARIABLE
def recursive_replace_variable(nested_list, var_changes):
    new_list = []
    for item in nested_list:
        if isinstance(item, list):
            # If the item is a list, recursively apply the replacement
            new_list.append(recursive_replace_variable(item, var_changes))
        elif item in var_changes:
            # If the item is a key in var_changes, replace it
            new_list.append(var_changes[item])
        else:
            # Otherwise, keep the original item
            new_list.append(item)
    return new_list


def wrapper_varchange(style_json, var_changes, layer_ids):
    modified_json = style_json.copy()

    for layer in modified_json['layers']:
        if layer['id'] in layer_ids:
            # Check and update 'fill-color' if present
            if 'fill-color' in layer.get('paint', {}):
                layer['paint']['fill-color'] = recursive_replace_variable(layer['paint']['fill-color'], var_changes)
            
            # Check and update 'text-field' if present
            if 'text-field' in layer.get('layout', {}):
                layer['layout']['text-field'] = recursive_replace_variable(layer['layout']['text-field'], var_changes)
    return modified_json


def replace_scale_colors_in_json(style_json, new_values, layer_ids):
    modified_json = style_json.copy()
    
    for layer in modified_json['layers']:
        if layer['id'] in layer_ids:
            for i, item in enumerate(layer['paint']['fill-color']):
                if isinstance(item, list) and item[0] == 'interpolate':
                    # Replace from the 3rd item onward, because the first three are ['interpolate', ['linear'], ['get', 'SOME_VARIABLE']]
                    layer['paint']['fill-color'][2][3:] = new_values
    return modified_json


import matplotlib.pyplot as plt
import matplotlib.colors

def get_colors_from_cmap(cmap_name, n_stops):
    """
    Get a list of colors in hex format from a given cmap.
    
    Parameters:
    - cmap_name (str): Name of the color map (e.g. "RdYlGn_r").
    - n_stops (int): Number of color stops you want.
    
    Returns:
    - List of colors in hex format.
    """
    cmap = plt.get_cmap(cmap_name)
    colors = [cmap(i / (n_stops-1)) for i in range(n_stops)]
    hex_colors = [matplotlib.colors.rgb2hex(color) for color in colors]
    return hex_colors


def apply_ARS_format_in_json(style_json, layer_ids, varname):
    modified_json = style_json.copy()

    for layer in modified_json['layers']:
        if layer['id'] in layer_ids:
            # Modify 'text-field' property
            layer['layout']['text-field'] = [
                "to-string",
                [
                    "*",
                    1000,
                    ["round", ["/", ["get", varname], 1000]]
                ]
            ]
            # # Modify 'text-size' property
            # layer['layout']['text-size'] = 12

            # # Modify 'text-opacity' and 'text-color' in 'paint' property
            # layer['paint']['text-opacity'] = [
            #     "interpolate",
            #     ["linear"],
            #     ["zoom"],
            #     9.9,
            #     0,
            #     10,
            #     0.8,
            #     21,
            #     0.8,
            #     22,
            #     0
            # ]
            # layer['paint']['text-color'] = "rgb(0, 0, 0)"

    return modified_json

In [19]:

# year_month = str(pd.Timestamp.now().year) + str(pd.Timestamp.now().month).zfill(2)
# year_month
# # year_month = '202309c'

In [20]:
template_json['sources']#['composite']['url']

{'composite': {'url': 'mapbox://mapbox.mapbox-streets-v8,mapbox.mapbox-terrain-v2,matuteiglesias2.income_M14202309,matuteiglesias2.ejido',
  'type': 'vector'}}

In [21]:
import numpy as np

In [22]:
import json
import requests
import pandas as pd

# Define necessary variables
username = 'matuteiglesias2'
access_token = 'sk.eyJ1IjoibWF0dXRlaWdsZXNpYXMyIiwiYSI6ImNrb3lvMWZyajAxZncycG8ycnJkaTI1ZjYifQ.LXJGImmBgQtWWrNOC1wTcA'
styleuploader ='sk.eyJ1IjoibWF0dXRlaWdsZXNpYXMyIiwiYSI6ImNsaHlnMjRrbjAwaHEzZ280Yzh3NTY1dW8ifQ.htipF1LHE9GXTUzXfhAwTw'

styles_info = pd.read_csv('./../data/info/mapbox_styles.csv') # Replace with the correct path to your CSV
# styles_info['source'] = styles_info['source'].apply(lambda x: x[:-6] + year_month)  ## not like this anymore


# Process each group and update the source column with the new versioned tileset name
for group in groups:
    # Get the base name and next available version
    tileset_name_base = f"{username}.income_{group}{year_month}"
    tileset_name, version = get_current_version(tileset_name_base, username)
    
    # Update the source column in styles_info
    styles_info['source'] = styles_info['source'].apply(lambda x: tileset_name if group in x else x)

    # Log the process
    print(f"Updated source for group {group} to {tileset_name}")

# # Save the updated styles_info DataFrame
# styles_info.to_csv('./../data/info/mapbox_styles.csv', index=False)

matuteiglesias2.income_H202408_v0
matuteiglesias2.income_H202408_v1
matuteiglesias2.income_H202408_v2
matuteiglesias2.income_H202408_v3
matuteiglesias2.income_H202408_v4
matuteiglesias2.income_H202408_v5
Updated source for group H to matuteiglesias2.income_H202408_v5
matuteiglesias2.income_P202408_v0
matuteiglesias2.income_P202408_v1
matuteiglesias2.income_P202408_v2
matuteiglesias2.income_P202408_v3
matuteiglesias2.income_P202408_v4
Updated source for group P to matuteiglesias2.income_P202408_v4
matuteiglesias2.income_M24202408_v0
matuteiglesias2.income_M24202408_v1
matuteiglesias2.income_M24202408_v2
matuteiglesias2.income_M24202408_v3
Updated source for group M24 to matuteiglesias2.income_M24202408_v3
matuteiglesias2.income_M6202408_v0
matuteiglesias2.income_M6202408_v1
matuteiglesias2.income_M6202408_v2
matuteiglesias2.income_M6202408_v3
Updated source for group M6 to matuteiglesias2.income_M6202408_v3
matuteiglesias2.income_M14202408_v0
matuteiglesias2.income_M14202408_v1
matuteiglesias2.income_M14202408_v2
matuteiglesias2.income_M14202408_v3
Updated source for group M14 to matuteiglesias2.income_M14202408_v3

In [23]:
styles_info

,title,id,source,variable,page_html,map_html
0,Pobreza (%). Menores de 6,cm0bhkwmq01c101qr5blpbqcw,matuteiglesias2.income_M6202408_v3,Pobreza_mean,men6porc.html,test_m6_pobreza.html
1,Pobreza (%). Menores de 14,cm0bhkyda000m01qrb0mg7m2g,matuteiglesias2.income_M14202408_v3,Pobreza_mean,men14porc.html,test_m14_pobreza.html
2,Pobreza (%). Mayores de 24,cm0bhl00201cn01qq06cy8672,matuteiglesias2.income_M24202408_v3,Pobreza_mean,may24porc.html,test_m24_pobreza.html
3,Pobreza (%). Personas,cm0bhl1ey00z101o0egd78uo0,matuteiglesias2.income_P202408_v4,Pobreza_mean,personasporc.html,test_pers_pobreza.html
4,Pobreza (%). Hogares,cm0bhl30z00z201o0b0s75kv2,matuteiglesias2.income_H202408_v5,Pobreza_mean,hogaresporc.html,test_hogar_pobreza.html
5,Indigencia (%). Menores de 6,cm0bhl4fy01c201qrffig9ijx,matuteiglesias2.income_M6202408_v3,Indigencia_mean,men6indporc.html,test_m6_indigencia.html
6,Indigencia (%). Personas,cm0bhl60n01cp01qq48iad56m,matuteiglesias2.income_P202408_v4,Indigencia_mean,personasindporc.html,test_personas_indigencia.html
7,Indigencia (%). Mayores de 24,cm0bhl7l701c301qre5vzgfzq,matuteiglesias2.income_M24202408_v3,Indigencia_mean,may24indporc.html,test_m24_indigencia.html
8,Indigencia (%). Hogares,cm0bhl95301c401qr1qilbt0o,matuteiglesias2.income_H202408_v5,Indigencia_mean,hogaresindporc.html,test_hogares_indigencia.html
9,Indigencia (%). Menores de 14,cm0bhlakj000n01qrdgfd2pbn,matuteiglesias2.income_M14202408_v3,Indigencia_mean,men14indporc.html,test_m14_indigencia.html
10,Canasta Alimentaria mediana (AR$). Hogares,cm0bhlc0g000o01qra3oe152g,matuteiglesias2.income_H202408_v5,CBA_median,cbamedhogares.html,test_cam_ars.html
11,Canasta Total mediana (AR$). Hogares,cm0bhldc700y001qv2deqbbqs,matuteiglesias2.income_H202408_v5,CBT_median,cbtmedars.html,test_ctm_ars.html
12,Ingreso mediano (AR$). Mayores de 24,cm0bhlf4001cq01qq4wla0rf8,matuteiglesias2.income_M24202408_v3,P47T_persona_median,itfmedmay24.html,test_im_ars.html
13,Ingreso Total Familiar mediano (AR$). Hogares,cm0bhlggy01c501qrfgr7hoqo,matuteiglesias2.income_H202408_v5,P47T_hogar_median,itfmedhogares.html,test_itf_ars.html

In [24]:


new_style_ids_dict = {}
# Loop through the styles and update each one
for _, row in styles_info.iterrows():
    template_json = json.load(open(STYLE_TEMPLATE))
    print("\n\nProcessing style:", row['title'])
    # style_id = row['id']
    # url = f"https://api.mapbox.com/styles/v1/{username}/{style_id}?access_token={access_token}"
    # response = requests.get(url)

    style_json = template_json.copy()

    # remove to avoid conflict
    style_json.pop('created', None)
    style_json.pop('modified', None)

    # Use the wrapper functions
    style_json = set_name(style_json, row['title']);
    style_json = set_center_and_zoom(style_json, [-58.3872, -34.5852], 11.2)
    print(row['source'], row['variable'])
    style_json = update_source_url(style_json, row['source'])
    # print()    

    layer_ids = ['text fracs', 'text dptos', 'text provs', 'fill fracs', 'fill dptos', 'fill provs']
    style_json = wrapper_varchange(style_json, {"Indigencia_mean": row['variable']}, 
                                   layer_ids=layer_ids)

    ## COLORES y ESCALA
    fill_layer_ids = ['fill fracs', 'fill dptos', 'fill provs']
    n_stops = 10

    # Determine the new range based on the title
    if 'Pobreza' in row['title']:
        cmap = 'RdYlGn_r'
        linspace_values = np.linspace(0, 0.6, n_stops)
    elif 'Indigencia' in row['title']:
        cmap = 'RdYlGn_r'
        linspace_values = np.linspace(0, 0.25, n_stops)
    elif 'Canasta Alimentaria' in row['title']:
        cmap = 'Reds'
        linspace_values = np.linspace(0, 300000, n_stops)
    elif 'Canasta Total' in row['title']:
        cmap = 'Blues'
        linspace_values = np.linspace(0, 600000, n_stops)
    elif 'Ingreso mediano' in row['title']:
        cmap = 'Greens'
        linspace_values = np.linspace(0, 600000, n_stops)
    elif 'Ingreso Total Familiar' in row['title']:
        cmap = 'Greens'
        linspace_values = np.linspace(0, 1200000, n_stops)

    # Round to .01 precision
    linspace_values = [round(value, 2) for value in linspace_values]

    if 'AR$' in row['title']:
        linspace_values = [round(value, -3) for value in linspace_values]

    color_changes = get_colors_from_cmap(cmap, n_stops)
    
    # Interleave scale values and colors
    new_values = [val for pair in zip(linspace_values, color_changes) for val in pair]

    # Update the style_json with the new scale and colors
    style_json = replace_scale_colors_in_json(style_json, new_values, fill_layer_ids)


    # AR$ format
    text_layer_ids = ['text provs', 'text dptos', 'text fracs']
    if "AR$" in row['title']:
        style_json = apply_ARS_format_in_json(style_json, text_layer_ids, row['variable'])


    ## Style Json Edit Completed. SHOW:
    for layer in style_json['layers']:
        if layer['id'] in ['fill fracs', 'fill dptos', 'fill provs']:
            print(layer['paint']['fill-color'])
        if layer['id'] in ['text fracs', 'text dptos', 'text provs']:
            print(layer['layout']['text-field'])

    # Upload the updated style JSON
        # Create new style
    response = requests.post(
        f"https://api.mapbox.com/styles/v1/{username}?access_token={styleuploader}",
        json=style_json
    )

    response_status_code = response.status_code

    if response_status_code == 201:
        style_id = response.json()['id']; new_style_ids_dict[row.name] = style_id; print(style_id)
        print(f"Style updated for {row['title']}.")
    else:
        print(f"Error updating style for {row['title']}. Status code: {response_status_code}")

    # Replace existing style (    if response_status_code == 200:)
    # response = requests.patch(
    #     f"https://api.mapbox.com/styles/v1/{username}/{style_id}?access_token={styleuploader}",
    #     json=style_data
    # )


    # Check if 'id' field is not empty
    if pd.notnull(row['id']):
        # Delete the old style
        delete_response = requests.delete(
            f"https://api.mapbox.com/styles/v1/{username}/{row['id']}?access_token={styleuploader}"
        )
        if delete_response.status_code == 204:
            print(f"Successfully deleted old style with ID {row['id']}.")
        else:
            print(f"Error deleting style with ID {row['id']}. Status code: {delete_response.status_code}")


    time.sleep(0.5)

# Add the new IDs to the dataframe
styles_info['id'] = styles_info.index.map(new_style_ids_dict)

# Save the updated dataframe to the CSV
styles_info.to_csv('./../data/info/mapbox_styles.csv', index=False)

Processing style: Pobreza (%). Menores de 6
matuteiglesias2.income_M6202408_v3 Pobreza_mean
mapbox://mapbox.mapbox-streets-v8,mapbox.mapbox-terrain-v2,matuteiglesias2.income_M6202408_v3,matuteiglesias2.ejido
['case', ['>', ['get', 'Total_sum'], 500], ['interpolate', ['linear'], ['get', 'Pobreza_mean'], 0.0, '#006837', 0.07, '#219c52', 0.13, '#73c264', 0.2, '#b7e075', 0.27, '#e9f6a1', 0.33, '#feeda1', 0.4, '#fdbf6f', 0.47, '#f67a49', 0.53, '#da362a', 0.6, '#a50026'], '#bfbfbf']
['case', ['>', ['get', 'Total_sum'], 2000], ['interpolate', ['linear'], ['get', 'Pobreza_mean'], 0.0, '#006837', 0.07, '#219c52', 0.13, '#73c264', 0.2, '#b7e075', 0.27, '#e9f6a1', 0.33, '#feeda1', 0.4, '#fdbf6f', 0.47, '#f67a49', 0.53, '#da362a', 0.6, '#a50026'], 'hsla(0, 0%, 31%, 0.3)']
['case', ['>', ['get', 'Total_sum'], 2000], ['interpolate', ['linear'], ['get', 'Pobreza_mean'], 0.0, '#006837', 0.07, '#219c52', 0.13, '#73c264', 0.2, '#b7e075', 0.27, '#e9f6a1', 0.33, '#feeda1', 0.4, '#fdbf6f', 0.47, '#f67a49', 0.53, '#da362a', 0.6, '#a50026'], '#bfbfbf']
['to-string', ['concat', ['round', ['*', 100, ['get', 'Pobreza_mean']]], '%']]
['to-string', ['concat', ['round', ['*', 100, ['get', 'Pobreza_mean']]], '%']]
['to-string', ['concat', ['round', ['*', 100, ['get', 'Pobreza_mean']]], '%']]
cm0cn8a1a011w01qv19gr564w
Style updated for Pobreza (%). Menores de 6.
Successfully deleted old style with ID cm0bhkwmq01c101qr5blpbqcw.


Processing style: Pobreza (%). Menores de 14
matuteiglesias2.income_M14202408_v3 Pobreza_mean
mapbox://mapbox.mapbox-streets-v8,mapbox.mapbox-terrain-v2,matuteiglesias2.income_M14202408_v3,matuteiglesias2.ejido
['case', ['>', ['get', 'Total_sum'], 500], ['interpolate', ['linear'], ['get', 'Pobreza_mean'], 0.0, '#006837', 0.07, '#219c52', 0.13, '#73c264', 0.2, '#b7e075', 0.27, '#e9f6a1', 0.33, '#feeda1', 0.4, '#fdbf6f', 0.47, '#f67a49', 0.53, '#da362a', 0.6, '#a50026'], '#bfbfbf']
['case', ['>', ['get', 'Total_sum'], 2000], ['interpolate', ['linear'], ['get', 'Pobreza_mean'], 0.0, '#006837', 0.07, '#219c52', 0.13, '#73c264', 0.2, '#b7e075', 0.27, '#e9f6a1', 0.33, '#feeda1', 0.4, '#fdbf6f', 0.47, '#f67a49', 0.53, '#da362a', 0.6, '#a50026'], 'hsla(0, 0%, 31%, 0.3)']
['case', ['>', ['get', 'Total_sum'], 2000], ['interpolate', ['linear'], ['get', 'Pobreza_mean'], 0.0, '#006837', 0.07, '#219c52', 0.13, '#73c264', 0.2, '#b7e075', 0.27, '#e9f6a1', 0.33, '#feeda1', 0.4, '#fdbf6f', 0.47, '#f67a49', 0.53, '#da362a', 0.6, '#a50026'], '#bfbfbf']
['to-string', ['concat', ['round', ['*', 100, ['get', 'Pobreza_mean']]], '%']]
['to-string', ['concat', ['round', ['*', 100, ['get', 'Pobreza_mean']]], '%']]
['to-string', ['concat', ['round', ['*', 100, ['get', 'Pobreza_mean']]], '%']]
cm0cn8bst011x01qvfux50nwb
Style updated for Pobreza (%). Menores de 14.
Successfully deleted old style with ID cm0bhkyda000m01qrb0mg7m2g.


Processing style: Pobreza (%). Mayores de 24
matuteiglesias2.income_M24202408_v3 Pobreza_mean
mapbox://mapbox.mapbox-streets-v8,mapbox.mapbox-terrain-v2,matuteiglesias2.income_M24202408_v3,matuteiglesias2.ejido
['case', ['>', ['get', 'Total_sum'], 500], ['interpolate', ['linear'], ['get', 'Pobreza_mean'], 0.0, '#006837', 0.07, '#219c52', 0.13, '#73c264', 0.2, '#b7e075', 0.27, '#e9f6a1', 0.33, '#feeda1', 0.4, '#fdbf6f', 0.47, '#f67a49', 0.53, '#da362a', 0.6, '#a50026'], '#bfbfbf']
['case', ['>', ['get', 'Total_sum'], 2000], ['interpolate', ['linear'], ['get', 'Pobreza_mean'], 0.0, '#006837', 0.07, '#219c52', 0.13, '#73c264', 0.2, '#b7e075', 0.27, '#e9f6a1', 0.33, '#feeda1', 0.4, '#fdbf6f', 0.47, '#f67a49', 0.53, '#da362a', 0.6, '#a50026'], 'hsla(0, 0%, 31%, 0.3)']
['case', ['>', ['get', 'Total_sum'], 2000], ['interpolate', ['linear'], ['get', 'Pobreza_mean'], 0.0, '#006837', 0.07, '#219c52', 0.13, '#73c264', 0.2, '#b7e075', 0.27, '#e9f6a1', 0.33, '#feeda1', 0.4, '#fdbf6f', 0.47, '#f67a49', 0.53, '#da362a', 0.6, '#a50026'], '#bfbfbf']
['to-string', ['concat', ['round', ['*', 100, ['get', 'Pobreza_mean']]], '%']]
['to-string', ['concat', ['round', ['*', 100, ['get', 'Pobreza_mean']]], '%']]
['to-string', ['concat', ['round', ['*', 100, ['get', 'Pobreza_mean']]], '%']]
cm0cn8d1i011y01qvhbvo2ri9
Style updated for Pobreza (%). Mayores de 24.
Successfully deleted old style with ID cm0bhl00201cn01qq06cy8672.


Processing style: Pobreza (%). Personas
matuteiglesias2.income_P202408_v4 Pobreza_mean
mapbox://mapbox.mapbox-streets-v8,mapbox.mapbox-terrain-v2,matuteiglesias2.income_P202408_v4,matuteiglesias2.ejido
['case', ['>', ['get', 'Total_sum'], 500], ['interpolate', ['linear'], ['get', 'Pobreza_mean'], 0.0, '#006837', 0.07, '#219c52', 0.13, '#73c264', 0.2, '#b7e075', 0.27, '#e9f6a1', 0.33, '#feeda1', 0.4, '#fdbf6f', 0.47, '#f67a49', 0.53, '#da362a', 0.6, '#a50026'], '#bfbfbf']
['case', ['>', ['get', 'Total_sum'], 2000], ['interpolate', ['linear'], ['get', 'Pobreza_mean'], 0.0, '#006837', 0.07, '#219c52', 0.13, '#73c264', 0.2, '#b7e075', 0.27, '#e9f6a1', 0.33, '#feeda1', 0.4, '#fdbf6f', 0.47, '#f67a49', 0.53, '#da362a', 0.6, '#a50026'], 'hsla(0, 0%, 31%, 0.3)']
['case', ['>', ['get', 'Total_sum'], 2000], ['interpolate', ['linear'], ['get', 'Pobreza_mean'], 0.0, '#006837', 0.07, '#219c52', 0.13, '#73c264', 0.2, '#b7e075', 0.27, '#e9f6a1', 0.33, '#feeda1', 0.4, '#fdbf6f', 0.47, '#f67a49', 0.53, '#da362a', 0.6, '#a50026'], '#bfbfbf']
['to-string', ['concat', ['round', ['*', 100, ['get', 'Pobreza_mean']]], '%']]
['to-string', ['concat', ['round', ['*', 100, ['get', 'Pobreza_mean']]], '%']]
['to-string', ['concat', ['round', ['*', 100, ['get', 'Pobreza_mean']]], '%']]
cm0cn8gqp011z01qvacmlgi6d
Style updated for Pobreza (%). Personas.
Successfully deleted old style with ID cm0bhl1ey00z101o0egd78uo0.


Processing style: Pobreza (%). Hogares
matuteiglesias2.income_H202408_v5 Pobreza_mean
mapbox://mapbox.mapbox-streets-v8,mapbox.mapbox-terrain-v2,matuteiglesias2.income_H202408_v5,matuteiglesias2.ejido
['case', ['>', ['get', 'Total_sum'], 500], ['interpolate', ['linear'], ['get', 'Pobreza_mean'], 0.0, '#006837', 0.07, '#219c52', 0.13, '#73c264', 0.2, '#b7e075', 0.27, '#e9f6a1', 0.33, '#feeda1', 0.4, '#fdbf6f', 0.47, '#f67a49', 0.53, '#da362a', 0.6, '#a50026'], '#bfbfbf']
['case', ['>', ['get', 'Total_sum'], 2000], ['interpolate', ['linear'], ['get', 'Pobreza_mean'], 0.0, '#006837', 0.07, '#219c52', 0.13, '#73c264', 0.2, '#b7e075', 0.27, '#e9f6a1', 0.33, '#feeda1', 0.4, '#fdbf6f', 0.47, '#f67a49', 0.53, '#da362a', 0.6, '#a50026'], 'hsla(0, 0%, 31%, 0.3)']
['case', ['>', ['get', 'Total_sum'], 2000], ['interpolate', ['linear'], ['get', 'Pobreza_mean'], 0.0, '#006837', 0.07, '#219c52', 0.13, '#73c264', 0.2, '#b7e075', 0.27, '#e9f6a1', 0.33, '#feeda1', 0.4, '#fdbf6f', 0.47, '#f67a49', 0.53, '#da362a', 0.6, '#a50026'], '#bfbfbf']
['to-string', ['concat', ['round', ['*', 100, ['get', 'Pobreza_mean']]], '%']]
['to-string', ['concat', ['round', ['*', 100, ['get', 'Pobreza_mean']]], '%']]
['to-string', ['concat', ['round', ['*', 100, ['get', 'Pobreza_mean']]], '%']]
cm0cn8i3g004k01qr79i3fh4z
Style updated for Pobreza (%). Hogares.
Successfully deleted old style with ID cm0bhl30z00z201o0b0s75kv2.


Processing style: Indigencia (%). Menores de 6
matuteiglesias2.income_M6202408_v3 Indigencia_mean
mapbox://mapbox.mapbox-streets-v8,mapbox.mapbox-terrain-v2,matuteiglesias2.income_M6202408_v3,matuteiglesias2.ejido
['case', ['>', ['get', 'Total_sum'], 500], ['interpolate', ['linear'], ['get', 'Indigencia_mean'], 0.0, '#006837', 0.03, '#219c52', 0.06, '#73c264', 0.08, '#b7e075', 0.11, '#e9f6a1', 0.14, '#feeda1', 0.17, '#fdbf6f', 0.19, '#f67a49', 0.22, '#da362a', 0.25, '#a50026'], '#bfbfbf']
['case', ['>', ['get', 'Total_sum'], 2000], ['interpolate', ['linear'], ['get', 'Indigencia_mean'], 0.0, '#006837', 0.03, '#219c52', 0.06, '#73c264', 0.08, '#b7e075', 0.11, '#e9f6a1', 0.14, '#feeda1', 0.17, '#fdbf6f', 0.19, '#f67a49', 0.22, '#da362a', 0.25, '#a50026'], 'hsla(0, 0%, 31%, 0.3)']
['case', ['>', ['get', 'Total_sum'], 2000], ['interpolate', ['linear'], ['get', 'Indigencia_mean'], 0.0, '#006837', 0.03, '#219c52', 0.06, '#73c264', 0.08, '#b7e075', 0.11, '#e9f6a1', 0.14, '#feeda1', 0.17, '#fdbf6f', 0.19, '#f67a49', 0.22, '#da362a', 0.25, '#a50026'], '#bfbfbf']
['to-string', ['concat', ['round', ['*', 100, ['get', 'Indigencia_mean']]], '%']]
['to-string', ['concat', ['round', ['*', 100, ['get', 'Indigencia_mean']]], '%']]
['to-string', ['concat', ['round', ['*', 100, ['get', 'Indigencia_mean']]], '%']]
cm0cn8jdx004l01qr621m0j9b
Style updated for Indigencia (%). Menores de 6.
Successfully deleted old style with ID cm0bhl4fy01c201qrffig9ijx.


Processing style: Indigencia (%). Personas
matuteiglesias2.income_P202408_v4 Indigencia_mean
mapbox://mapbox.mapbox-streets-v8,mapbox.mapbox-terrain-v2,matuteiglesias2.income_P202408_v4,matuteiglesias2.ejido
['case', ['>', ['get', 'Total_sum'], 500], ['interpolate', ['linear'], ['get', 'Indigencia_mean'], 0.0, '#006837', 0.03, '#219c52', 0.06, '#73c264', 0.08, '#b7e075', 0.11, '#e9f6a1', 0.14, '#feeda1', 0.17, '#fdbf6f', 0.19, '#f67a49', 0.22, '#da362a', 0.25, '#a50026'], '#bfbfbf']
['case', ['>', ['get', 'Total_sum'], 2000], ['interpolate', ['linear'], ['get', 'Indigencia_mean'], 0.0, '#006837', 0.03, '#219c52', 0.06, '#73c264', 0.08, '#b7e075', 0.11, '#e9f6a1', 0.14, '#feeda1', 0.17, '#fdbf6f', 0.19, '#f67a49', 0.22, '#da362a', 0.25, '#a50026'], 'hsla(0, 0%, 31%, 0.3)']
['case', ['>', ['get', 'Total_sum'], 2000], ['interpolate', ['linear'], ['get', 'Indigencia_mean'], 0.0, '#006837', 0.03, '#219c52', 0.06, '#73c264', 0.08, '#b7e075', 0.11, '#e9f6a1', 0.14, '#feeda1', 0.17, '#fdbf6f', 0.19, '#f67a49', 0.22, '#da362a', 0.25, '#a50026'], '#bfbfbf']
['to-string', ['concat', ['round', ['*', 100, ['get', 'Indigencia_mean']]], '%']]
['to-string', ['concat', ['round', ['*', 100, ['get', 'Indigencia_mean']]], '%']]
['to-string', ['concat', ['round', ['*', 100, ['get', 'Indigencia_mean']]], '%']]
cm0cn8kvl013e01o05zdq697p
Style updated for Indigencia (%). Personas.
Successfully deleted old style with ID cm0bhl60n01cp01qq48iad56m.


Processing style: Indigencia (%). Mayores de 24
matuteiglesias2.income_M24202408_v3 Indigencia_mean
mapbox://mapbox.mapbox-streets-v8,mapbox.mapbox-terrain-v2,matuteiglesias2.income_M24202408_v3,matuteiglesias2.ejido
['case', ['>', ['get', 'Total_sum'], 500], ['interpolate', ['linear'], ['get', 'Indigencia_mean'], 0.0, '#006837', 0.03, '#219c52', 0.06, '#73c264', 0.08, '#b7e075', 0.11, '#e9f6a1', 0.14, '#feeda1', 0.17, '#fdbf6f', 0.19, '#f67a49', 0.22, '#da362a', 0.25, '#a50026'], '#bfbfbf']
['case', ['>', ['get', 'Total_sum'], 2000], ['interpolate', ['linear'], ['get', 'Indigencia_mean'], 0.0, '#006837', 0.03, '#219c52', 0.06, '#73c264', 0.08, '#b7e075', 0.11, '#e9f6a1', 0.14, '#feeda1', 0.17, '#fdbf6f', 0.19, '#f67a49', 0.22, '#da362a', 0.25, '#a50026'], 'hsla(0, 0%, 31%, 0.3)']
['case', ['>', ['get', 'Total_sum'], 2000], ['interpolate', ['linear'], ['get', 'Indigencia_mean'], 0.0, '#006837', 0.03, '#219c52', 0.06, '#73c264', 0.08, '#b7e075', 0.11, '#e9f6a1', 0.14, '#feeda1', 0.17, '#fdbf6f', 0.19, '#f67a49', 0.22, '#da362a', 0.25, '#a50026'], '#bfbfbf']
['to-string', ['concat', ['round', ['*', 100, ['get', 'Indigencia_mean']]], '%']]
['to-string', ['concat', ['round', ['*', 100, ['get', 'Indigencia_mean']]], '%']]
['to-string', ['concat', ['round', ['*', 100, ['get', 'Indigencia_mean']]], '%']]
cm0cn8m4e013f01o00uucdv1f
Style updated for Indigencia (%). Mayores de 24.
Successfully deleted old style with ID cm0bhl7l701c301qre5vzgfzq.


Processing style: Indigencia (%). Hogares
matuteiglesias2.income_H202408_v5 Indigencia_mean
mapbox://mapbox.mapbox-streets-v8,mapbox.mapbox-terrain-v2,matuteiglesias2.income_H202408_v5,matuteiglesias2.ejido
['case', ['>', ['get', 'Total_sum'], 500], ['interpolate', ['linear'], ['get', 'Indigencia_mean'], 0.0, '#006837', 0.03, '#219c52', 0.06, '#73c264', 0.08, '#b7e075', 0.11, '#e9f6a1', 0.14, '#feeda1', 0.17, '#fdbf6f', 0.19, '#f67a49', 0.22, '#da362a', 0.25, '#a50026'], '#bfbfbf']
['case', ['>', ['get', 'Total_sum'], 2000], ['interpolate', ['linear'], ['get', 'Indigencia_mean'], 0.0, '#006837', 0.03, '#219c52', 0.06, '#73c264', 0.08, '#b7e075', 0.11, '#e9f6a1', 0.14, '#feeda1', 0.17, '#fdbf6f', 0.19, '#f67a49', 0.22, '#da362a', 0.25, '#a50026'], 'hsla(0, 0%, 31%, 0.3)']
['case', ['>', ['get', 'Total_sum'], 2000], ['interpolate', ['linear'], ['get', 'Indigencia_mean'], 0.0, '#006837', 0.03, '#219c52', 0.06, '#73c264', 0.08, '#b7e075', 0.11, '#e9f6a1', 0.14, '#feeda1', 0.17, '#fdbf6f', 0.19, '#f67a49', 0.22, '#da362a', 0.25, '#a50026'], '#bfbfbf']
['to-string', ['concat', ['round', ['*', 100, ['get', 'Indigencia_mean']]], '%']]
['to-string', ['concat', ['round', ['*', 100, ['get', 'Indigencia_mean']]], '%']]
['to-string', ['concat', ['round', ['*', 100, ['get', 'Indigencia_mean']]], '%']]
cm0cn8naj013g01o0h12pcbbb
Style updated for Indigencia (%). Hogares.
Successfully deleted old style with ID cm0bhl95301c401qr1qilbt0o.


Processing style: Indigencia (%). Menores de 14
matuteiglesias2.income_M14202408_v3 Indigencia_mean
mapbox://mapbox.mapbox-streets-v8,mapbox.mapbox-terrain-v2,matuteiglesias2.income_M14202408_v3,matuteiglesias2.ejido
['case', ['>', ['get', 'Total_sum'], 500], ['interpolate', ['linear'], ['get', 'Indigencia_mean'], 0.0, '#006837', 0.03, '#219c52', 0.06, '#73c264', 0.08, '#b7e075', 0.11, '#e9f6a1', 0.14, '#feeda1', 0.17, '#fdbf6f', 0.19, '#f67a49', 0.22, '#da362a', 0.25, '#a50026'], '#bfbfbf']
['case', ['>', ['get', 'Total_sum'], 2000], ['interpolate', ['linear'], ['get', 'Indigencia_mean'], 0.0, '#006837', 0.03, '#219c52', 0.06, '#73c264', 0.08, '#b7e075', 0.11, '#e9f6a1', 0.14, '#feeda1', 0.17, '#fdbf6f', 0.19, '#f67a49', 0.22, '#da362a', 0.25, '#a50026'], 'hsla(0, 0%, 31%, 0.3)']
['case', ['>', ['get', 'Total_sum'], 2000], ['interpolate', ['linear'], ['get', 'Indigencia_mean'], 0.0, '#006837', 0.03, '#219c52', 0.06, '#73c264', 0.08, '#b7e075', 0.11, '#e9f6a1', 0.14, '#feeda1', 0.17, '#fdbf6f', 0.19, '#f67a49', 0.22, '#da362a', 0.25, '#a50026'], '#bfbfbf']
['to-string', ['concat', ['round', ['*', 100, ['get', 'Indigencia_mean']]], '%']]
['to-string', ['concat', ['round', ['*', 100, ['get', 'Indigencia_mean']]], '%']]
['to-string', ['concat', ['round', ['*', 100, ['get', 'Indigencia_mean']]], '%']]
cm0cn8okh004m01qr8xs2hf4c
Style updated for Indigencia (%). Menores de 14.
Successfully deleted old style with ID cm0bhlakj000n01qrdgfd2pbn.


Processing style: Canasta Alimentaria mediana (AR$). Hogares
matuteiglesias2.income_H202408_v5 CBA_median
mapbox://mapbox.mapbox-streets-v8,mapbox.mapbox-terrain-v2,matuteiglesias2.income_H202408_v5,matuteiglesias2.ejido
['case', ['>', ['get', 'Total_sum'], 500], ['interpolate', ['linear'], ['get', 'CBA_median'], 0.0, '#fff5f0', 33000.0, '#fee3d6', 67000.0, '#fcc4ad', 100000.0, '#fca082', 133000.0, '#fb7c5c', 167000.0, '#f6553c', 200000.0, '#e32f27', 233000.0, '#c2161b', 267000.0, '#9d0d14', 300000.0, '#67000d'], '#bfbfbf']
['case', ['>', ['get', 'Total_sum'], 2000], ['interpolate', ['linear'], ['get', 'CBA_median'], 0.0, '#fff5f0', 33000.0, '#fee3d6', 67000.0, '#fcc4ad', 100000.0, '#fca082', 133000.0, '#fb7c5c', 167000.0, '#f6553c', 200000.0, '#e32f27', 233000.0, '#c2161b', 267000.0, '#9d0d14', 300000.0, '#67000d'], 'hsla(0, 0%, 31%, 0.3)']
['case', ['>', ['get', 'Total_sum'], 2000], ['interpolate', ['linear'], ['get', 'CBA_median'], 0.0, '#fff5f0', 33000.0, '#fee3d6', 67000.0, '#fcc4ad', 100000.0, '#fca082', 133000.0, '#fb7c5c', 167000.0, '#f6553c', 200000.0, '#e32f27', 233000.0, '#c2161b', 267000.0, '#9d0d14', 300000.0, '#67000d'], '#bfbfbf']
['to-string', ['*', 1000, ['round', ['/', ['get', 'CBA_median'], 1000]]]]
['to-string', ['*', 1000, ['round', ['/', ['get', 'CBA_median'], 1000]]]]
['to-string', ['*', 1000, ['round', ['/', ['get', 'CBA_median'], 1000]]]]
cm0cn8rrj01fp01qrbendeskg
Style updated for Canasta Alimentaria mediana (AR$). Hogares.
Successfully deleted old style with ID cm0bhlc0g000o01qra3oe152g.


Processing style: Canasta Total mediana (AR$). Hogares
matuteiglesias2.income_H202408_v5 CBT_median
mapbox://mapbox.mapbox-streets-v8,mapbox.mapbox-terrain-v2,matuteiglesias2.income_H202408_v5,matuteiglesias2.ejido
['case', ['>', ['get', 'Total_sum'], 500], ['interpolate', ['linear'], ['get', 'CBT_median'], 0.0, '#f7fbff', 67000.0, '#e1edf8', 133000.0, '#ccdff1', 200000.0, '#abd0e6', 267000.0, '#82bbdb', 333000.0, '#58a1cf', 400000.0, '#3787c0', 467000.0, '#1b69af', 533000.0, '#084d96', 600000.0, '#08306b'], '#bfbfbf']
['case', ['>', ['get', 'Total_sum'], 2000], ['interpolate', ['linear'], ['get', 'CBT_median'], 0.0, '#f7fbff', 67000.0, '#e1edf8', 133000.0, '#ccdff1', 200000.0, '#abd0e6', 267000.0, '#82bbdb', 333000.0, '#58a1cf', 400000.0, '#3787c0', 467000.0, '#1b69af', 533000.0, '#084d96', 600000.0, '#08306b'], 'hsla(0, 0%, 31%, 0.3)']
['case', ['>', ['get', 'Total_sum'], 2000], ['interpolate', ['linear'], ['get', 'CBT_median'], 0.0, '#f7fbff', 67000.0, '#e1edf8', 133000.0, '#ccdff1', 200000.0, '#abd0e6', 267000.0, '#82bbdb', 333000.0, '#58a1cf', 400000.0, '#3787c0', 467000.0, '#1b69af', 533000.0, '#084d96', 600000.0, '#08306b'], '#bfbfbf']
['to-string', ['*', 1000, ['round', ['/', ['get', 'CBT_median'], 1000]]]]
['to-string', ['*', 1000, ['round', ['/', ['get', 'CBT_median'], 1000]]]]
['to-string', ['*', 1000, ['round', ['/', ['get', 'CBT_median'], 1000]]]]
cm0cn8trk01g001qqcp3jcva2
Style updated for Canasta Total mediana (AR$). Hogares.
Successfully deleted old style with ID cm0bhldc700y001qv2deqbbqs.


Processing style: Ingreso mediano (AR$). Mayores de 24
matuteiglesias2.income_M24202408_v3 P47T_persona_median
mapbox://mapbox.mapbox-streets-v8,mapbox.mapbox-terrain-v2,matuteiglesias2.income_M24202408_v3,matuteiglesias2.ejido
['case', ['>', ['get', 'Total_sum'], 500], ['interpolate', ['linear'], ['get', 'P47T_persona_median'], 0.0, '#f7fcf5', 67000.0, '#e7f6e3', 133000.0, '#ceecc8', 200000.0, '#aedea7', 267000.0, '#88ce87', 333000.0, '#5db96b', 400000.0, '#37a055', 467000.0, '#1a843f', 533000.0, '#00682a', 600000.0, '#00441b'], '#bfbfbf']
['case', ['>', ['get', 'Total_sum'], 2000], ['interpolate', ['linear'], ['get', 'P47T_persona_median'], 0.0, '#f7fcf5', 67000.0, '#e7f6e3', 133000.0, '#ceecc8', 200000.0, '#aedea7', 267000.0, '#88ce87', 333000.0, '#5db96b', 400000.0, '#37a055', 467000.0, '#1a843f', 533000.0, '#00682a', 600000.0, '#00441b'], 'hsla(0, 0%, 31%, 0.3)']
['case', ['>', ['get', 'Total_sum'], 2000], ['interpolate', ['linear'], ['get', 'P47T_persona_median'], 0.0, '#f7fcf5', 67000.0, '#e7f6e3', 133000.0, '#ceecc8', 200000.0, '#aedea7', 267000.0, '#88ce87', 333000.0, '#5db96b', 400000.0, '#37a055', 467000.0, '#1a843f', 533000.0, '#00682a', 600000.0, '#00441b'], '#bfbfbf']
['to-string', ['*', 1000, ['round', ['/', ['get', 'P47T_persona_median'], 1000]]]]
['to-string', ['*', 1000, ['round', ['/', ['get', 'P47T_persona_median'], 1000]]]]
['to-string', ['*', 1000, ['round', ['/', ['get', 'P47T_persona_median'], 1000]]]]
cm0cn8v0q01fq01qrf7p6hs2d
Style updated for Ingreso mediano (AR$). Mayores de 24.
Successfully deleted old style with ID cm0bhlf4001cq01qq4wla0rf8.


Processing style: Ingreso Total Familiar mediano (AR$). Hogares
matuteiglesias2.income_H202408_v5 P47T_hogar_median
mapbox://mapbox.mapbox-streets-v8,mapbox.mapbox-terrain-v2,matuteiglesias2.income_H202408_v5,matuteiglesias2.ejido
['case', ['>', ['get', 'Total_sum'], 500], ['interpolate', ['linear'], ['get', 'P47T_hogar_median'], 0.0, '#f7fcf5', 133000.0, '#e7f6e3', 267000.0, '#ceecc8', 400000.0, '#aedea7', 533000.0, '#88ce87', 667000.0, '#5db96b', 800000.0, '#37a055', 933000.0, '#1a843f', 1067000.0, '#00682a', 1200000.0, '#00441b'], '#bfbfbf']
['case', ['>', ['get', 'Total_sum'], 2000], ['interpolate', ['linear'], ['get', 'P47T_hogar_median'], 0.0, '#f7fcf5', 133000.0, '#e7f6e3', 267000.0, '#ceecc8', 400000.0, '#aedea7', 533000.0, '#88ce87', 667000.0, '#5db96b', 800000.0, '#37a055', 933000.0, '#1a843f', 1067000.0, '#00682a', 1200000.0, '#00441b'], 'hsla(0, 0%, 31%, 0.3)']

### Actualiza estilos en la pagina web

In [25]:
import pandas as pd
import re

def update_style_id_in_file(filename, new_style_id):
    with open(filename, 'r') as file:
        file_contents = file.read()
        
    # Use a regular expression to replace style ID in the file content
    pattern = r"style: 'mapbox://styles/matuteiglesias2/[^']*'"
    replacement = f"style: 'mapbox://styles/matuteiglesias2/{new_style_id}'"
    new_content = re.sub(pattern, replacement, file_contents)
    
    with open(filename, 'w') as file:
        file.write(new_content)

        

# 1. Read the data file
styles_info = pd.read_csv('./../data/info/mapbox_styles.csv')

# 2. Iterate over each map HTML file you want to update
web_path = './../../../Documents/link/Pobreza/maps/mbox/'
for _, row in styles_info.iterrows():
    map_html_file = web_path + row['map_html']
    new_style_id = row['id']
    
    # 3 & 4. Update the style ID in the file
    update_style_id_in_file(map_html_file, new_style_id)

In [26]:
import pandas as pd

In [27]:
pd.read_csv('./../data/info/mapbox_styles.csv')

,title,id,source,variable,page_html,map_html
0,Pobreza (%). Menores de 6,cm0cn8a1a011w01qv19gr564w,matuteiglesias2.income_M6202408_v3,Pobreza_mean,men6porc.html,test_m6_pobreza.html
1,Pobreza (%). Menores de 14,cm0cn8bst011x01qvfux50nwb,matuteiglesias2.income_M14202408_v3,Pobreza_mean,men14porc.html,test_m14_pobreza.html
2,Pobreza (%). Mayores de 24,cm0cn8d1i011y01qvhbvo2ri9,matuteiglesias2.income_M24202408_v3,Pobreza_mean,may24porc.html,test_m24_pobreza.html
3,Pobreza (%). Personas,cm0cn8gqp011z01qvacmlgi6d,matuteiglesias2.income_P202408_v4,Pobreza_mean,personasporc.html,test_pers_pobreza.html
4,Pobreza (%). Hogares,cm0cn8i3g004k01qr79i3fh4z,matuteiglesias2.income_H202408_v5,Pobreza_mean,hogaresporc.html,test_hogar_pobreza.html
5,Indigencia (%). Menores de 6,cm0cn8jdx004l01qr621m0j9b,matuteiglesias2.income_M6202408_v3,Indigencia_mean,men6indporc.html,test_m6_indigencia.html
6,Indigencia (%). Personas,cm0cn8kvl013e01o05zdq697p,matuteiglesias2.income_P202408_v4,Indigencia_mean,personasindporc.html,test_personas_indigencia.html
7,Indigencia (%). Mayores de 24,cm0cn8m4e013f01o00uucdv1f,matuteiglesias2.income_M24202408_v3,Indigencia_mean,may24indporc.html,test_m24_indigencia.html
8,Indigencia (%). Hogares,cm0cn8naj013g01o0h12pcbbb,matuteiglesias2.income_H202408_v5,Indigencia_mean,hogaresindporc.html,test_hogares_indigencia.html
9,Indigencia (%). Menores de 14,cm0cn8okh004m01qr8xs2hf4c,matuteiglesias2.income_M14202408_v3,Indigencia_mean,men14indporc.html,test_m14_indigencia.html
10,Canasta Alimentaria mediana (AR$). Hogares,cm0cn8rrj01fp01qrbendeskg,matuteiglesias2.income_H202408_v5,CBA_median,cbamedhogares.html,test_cam_ars.html
11,Canasta Total mediana (AR$). Hogares,cm0cn8trk01g001qqcp3jcva2,matuteiglesias2.income_H202408_v5,CBT_median,cbtmedars.html,test_ctm_ars.html
12,Ingreso mediano (AR$). Mayores de 24,cm0cn8v0q01fq01qrf7p6hs2d,matuteiglesias2.income_M24202408_v3,P47T_persona_median,itfmedmay24.html,test_im_ars.html
13,Ingreso Total Familiar mediano (AR$). Hogares,cm0cn8waf01g101qqfvbn2h1x,matuteiglesias2.income_H202408_v5,P47T_hogar_median,itfmedhogares.html,test_itf_ars.html